default_language_version:
    python: python3.10.6
default_stages: [commit]
repos:
-   repo: https://github.com/asottile/pyupgrade
    rev: v3.1.0
    hooks:
    -   id: pyupgrade
        language_version: python3.10.6
        args:
            - --py3-plus
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: detect-private-key
    -   id: name-tests-test
        args:
        - --pytest-test-first
        exclude: ^store/tests/fixtures
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21  # Use the revision sha / tag you want to point at
    hooks:
    -   id: isort
-   repo: https://github.com/ambv/black
    rev: 22.3.0
    hooks:
    -   id: black
        language_version: python3.10.6
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.2
    hooks:
    -   id: flake8
        language_version: python3.10.6
        args:
        - --append-config=store/.flake8
        additional_dependencies:
            - 'flake8-future-import==0.4.6'
            - 'flake8-formatter-abspath==1.0.1'
            - 'flake8-mock==0.3'

-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.800'
    hooks:
    -   id: mypy
        language_version: python3.10.6
        entry: bash -c 'make pipeline-backend-mypy'
        additional_dependencies:
            - 'mypy-extensions==0.4.3'
            - 'sqlalchemy-stubs==0.4'
            - 'typing-extensions==3.10.0.0'
