version: '3.8'

services:
  web:
    build:
      context: store
      target: backend_web
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./store:/usr/src/app
    ports:
      - 8000:8000
    env_file:
      - web.env
    links:
      - db
    networks:
      - intranet

  db:
    image: postgres:13.4
    env_file:
      - db.env
    networks:
      - intranet

networks:
  intranet:
    driver: bridge