[tool.poetry]
name = "store"
version = "0.1.0"
description = ""
authors = ["eloy <eloy.colell@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry.group.dev.dependencies]
docker-compose = "^1.29.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
