"""add batch_tracked column and update product constraints.

Revision ID: 903c8ec67501
Revises: 5629d2050167
Create Date: 2022-11-21 12:46:35.964805

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision = '903c8ec67501'
down_revision = '5629d2050167'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('batch_tracked', sa.Boolean(), nullable=False))
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('product', 'purchase_uom',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_unique_constraint(None, 'product', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'product', type_='unique')
    op.alter_column('product', 'purchase_uom',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('product', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('product', 'batch_tracked')
    # ### end Alembic commands ###
